const DIFFICULTY = 4;
const MINE_RATE = 10000;
const INITIAL_BALANCE = 500;
const MINING_REWORD = 50;
const TOTAL_TO_SUPPLY = 18000000

module.exports={DIFFICULTY, MINE_RATE, INITIAL_BALANCE, MINING_REWORD, TOTAL_TO_SUPPLY}